### ISSUE TITLE
ARRR equihash coinbaseaux flags is empty

### ISSUE THREAD

**Issue by 49handyman** [blinkhash/foundation-stratum#9]
komodo doesnt seem to have coinbaseaux field in the json response.

let me know if i screwed something up.

a zcash config would be nice too. i tried to find one with no luck. i spent 3 hours digging thru komodo source just to confirm a few parameters were correct.

they may stil be wrong.

additional problem.

```Error: RF1ZgZEhEzHiPkYsQV5mhswY78Dvba84JP has no matching Script```

**Comment by blinkhash** [comment]
Sorry it wasn’t more clear, but Foundation doesn’t currently support Equihash coins. I integrated the algorithm w/ scripts/main/algorithms.js but there’s a few more stratum changes needed to be made in order to ensure that everything works properly. I have it listed on my todo list but it’s not currently a priority as I’m working on finishing up platform functionality first. I’ll post a working configuration to https://github.com/blinkhash/foundation-configurations as soon as possible. To stay up-to-date on Foundation developments and to find exactly when items are released, make sure to join the Discord—I’m much more active there.
